### ISSUE TITLE
stack smashing detected

### ISSUE THREAD

**Issue by Alica-cmd** [Kyle-ak/imu_tk#8]
./test_imu_calib test_data/xsens_acc.mat test_data/xsens_gyro.mat 

Importing IMU data from the Matlab matrix file : test_data/xsens_acc.mat
Importing IMU data from the Matlab matrix file : test_data/xsens_gyro.mat
*** stack smashing detected ***: terminated
Aborted (core dumped)

**Comment by spockman66** [comment]
> ./test_imu_calib test_data/xsens_acc.mat test_data/xsens_gyro.mat
> 
> Importing IMU data from the Matlab matrix file : test_data/xsens_acc.mat
> Importing IMU data from the Matlab matrix file : test_data/xsens_gyro.mat
> *** stack smashing detected ***: terminated
> Aborted (core dumped)

I met the same problem as you did, have you fixed that?

**Comment by spockman66** [comment]
![image](https://user-images.githubusercontent.com/42925134/126287768-f2741782-aa9b-4d88-ba83-b0646e1ab94a.png)
just add "add_compile_options(-g  -ggdb -O0 -Wall   -fstack-protector-all -march=native -fnon-call-exceptions)" in CMakeLists.txt, then recompile and rebuild, it will be ok.

**Comment by Thirtysix66** [comment]
@spockman66 Thanks! Just curious, could you share why it works now?
